### ISSUE TITLE
提示不存在

### ISSUE THREAD

**Issue by lihulanxx** [Leif160519/ansible-linux#2]
跑config.yml 时的PLAY [13.Rewrite cron templates]    提示/var/spool/cron/crontabs does not exist

**Comment by Leif160519** [comment]
> 跑config.yml 时的PLAY [13.Rewrite cron templates] 提示/var/spool/cron/crontabs does not exist

请问目标主机的系统版本是什么，ssh上去看下该目录是否真的不存在呢，正常来讲，这个路径都是存在的，crontab -e存储的定时任务都存储在这个路径下的

**Comment by lihulanxx** [comment]
> > 跑config.yml 时的PLAY [13.Rewrite cron templates] 提示/var/spool/cron/crontabs does not exist
> 
> 请问目标主机的系统版本是什么，ssh上去看下该目录是否真的不存在呢，正常来讲，这个路径都是存在的，crontab -e存储的定时任务都存储在这个路径下的

[root@localhost]# uname -a 
Linux localhost 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[root@localhost]# cd /var/spool/cron/    
[root@localhost]/var/spool/cron# ll
总用量 4
-rw-------. 1 root root 51 5月   2 12:37 root
[root@localhost]/var/spool/cron# 
我是跑在vmvare虚拟机上的,也只是单独跑了这一个config.yml

**Comment by Leif160519** [comment]
修复了，centos和ubuntu的路径还有点区别，我做了系统区分
